// GLSL shader autogenerated by cg2glsl.py.
#if defined(VERTEX)

#if __VERSION__ >= 130
#define COMPAT_VARYING out
#define COMPAT_ATTRIBUTE in
#define COMPAT_TEXTURE texture
#else
#define COMPAT_VARYING varying
#define COMPAT_ATTRIBUTE attribute
#define COMPAT_TEXTURE texture2D
#endif

#ifdef GL_ES
#define COMPAT_PRECISION mediump
#else
#define COMPAT_PRECISION
#endif
COMPAT_VARYING     vec4 _color1;
COMPAT_VARYING     float _frame_rotation;
struct input_dummy {
    vec2 _video_size;
    vec2 _texture_size;
    vec2 _output_dummy_size;
    float _frame_count;
    float _frame_direction;
    float _frame_rotation;
};
struct output_dummy {
    vec4 _color1;
};
vec4 _oPosition1;
input_dummy _IN1;
vec4 _r0014;
vec4 _r0016;
vec2 _r0018;
vec2 _v0018;
COMPAT_ATTRIBUTE vec4 VertexCoord;
COMPAT_ATTRIBUTE vec4 COLOR;
COMPAT_ATTRIBUTE vec4 TexCoord;
COMPAT_VARYING vec4 COL0;
COMPAT_VARYING vec4 TEX0;
COMPAT_VARYING vec4 TEX1;
 
uniform mat4 MVPMatrix;
uniform int FrameDirection;
uniform int FrameCount;
uniform COMPAT_PRECISION vec2 OutputSize;
uniform COMPAT_PRECISION vec2 TextureSize;
uniform COMPAT_PRECISION vec2 InputSize;
void main()
{
    vec4 _oColor;
    vec2 _otexCoord;
    vec2 _otexCoord1;
    vec2 _shift;
    _r0014 = VertexCoord.x*MVPMatrix[0];
    _r0014 = _r0014 + VertexCoord.y*MVPMatrix[1];
    _r0014 = _r0014 + VertexCoord.z*MVPMatrix[2];
    _r0014 = _r0014 + VertexCoord.w*MVPMatrix[3];
    _r0016 = _r0014.x*vec4( 1.99000001E+00, 0.00000000E+00, 0.00000000E+00, 0.00000000E+00);
    _r0016 = _r0016 + _r0014.y*vec4( 0.00000000E+00, 8.00000012E-01, 0.00000000E+00, 0.00000000E+00);
    _r0016 = _r0016 + _r0014.z*vec4( 0.00000000E+00, 0.00000000E+00, 1.00000000E+00, 0.00000000E+00);
    _r0016 = _r0016 + _r0014.w*vec4( 0.00000000E+00, 0.00000000E+00, 0.00000000E+00, 1.00000000E+00);
    _oPosition1 = _r0016;
    _oColor = COLOR;
    _shift = (5.00000000E-01*InputSize)/TextureSize;
    _otexCoord = (TexCoord.xy - _shift)/5.09999990E-01 + _shift;
    _v0018 = TexCoord.xy - _shift;
    _r0018 = _v0018.x*vec2( -1.00000000E+00, 0.00000000E+00);
    _r0018 = _r0018 + _v0018.y*vec2( 0.00000000E+00, -1.00000000E+00);
    _otexCoord1 = _r0018/5.09999990E-01 + _shift;
    gl_Position = _r0016;
    COL0 = COLOR;
    TEX0.xy = _otexCoord;
    TEX1.xy = _otexCoord1;
} 
#elif defined(FRAGMENT)

#if __VERSION__ >= 130
#define COMPAT_VARYING in
#define COMPAT_TEXTURE texture
out vec4 FragColor;
#else
#define COMPAT_VARYING varying
#define FragColor gl_FragColor
#define COMPAT_TEXTURE texture2D
#endif

#ifdef GL_ES
#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
#else
precision mediump float;
#endif
#define COMPAT_PRECISION mediump
#else
#define COMPAT_PRECISION
#endif
COMPAT_VARYING     vec4 _color;
COMPAT_VARYING     float _frame_rotation;
struct input_dummy {
    vec2 _video_size;
    vec2 _texture_size;
    vec2 _output_dummy_size;
    float _frame_count;
    float _frame_direction;
    float _frame_rotation;
};
struct output_dummy {
    vec4 _color;
};
vec4 _TMP1;
vec4 _TMP0;
uniform sampler2D Texture;
vec2 _c0005;
vec2 _c0007;
COMPAT_VARYING vec4 TEX0;
COMPAT_VARYING vec4 TEX1;
 
uniform int FrameDirection;
uniform int FrameCount;
uniform COMPAT_PRECISION vec2 OutputSize;
uniform COMPAT_PRECISION vec2 TextureSize;
uniform COMPAT_PRECISION vec2 InputSize;
void main()
{
    output_dummy _OUT;
    _c0005 = TEX0.xy + vec2( 0.00000000E+00, -2.34999999E-01);
    _TMP0 = COMPAT_TEXTURE(Texture, _c0005);
    _c0007 = TEX1.xy + vec2( 0.00000000E+00, -2.34999999E-01);
    _TMP1 = COMPAT_TEXTURE(Texture, _c0007);
    _OUT._color = _TMP0 + _TMP1;
    FragColor = _OUT._color;
    return;
} 
#endif
