// GLSL shader autogenerated by cg2glsl.py.
#if defined(VERTEX)

#if __VERSION__ >= 130
#define COMPAT_VARYING out
#define COMPAT_ATTRIBUTE in
#define COMPAT_TEXTURE texture
#else
#define COMPAT_VARYING varying
#define COMPAT_ATTRIBUTE attribute
#define COMPAT_TEXTURE texture2D
#endif

#ifdef GL_ES
#define COMPAT_PRECISION mediump
#else
#define COMPAT_PRECISION
#endif
struct input_dummy {
    vec2 _video_size;
    vec2 _texture_size;
    vec2 _output_dummy_size;
};
vec4 _oPosition1;
vec4 _r0005;
COMPAT_ATTRIBUTE vec4 VertexCoord;
COMPAT_ATTRIBUTE vec4 TexCoord;
COMPAT_VARYING vec4 TEX0;
 
uniform mat4 MVPMatrix;
uniform int FrameDirection;
uniform int FrameCount;
uniform COMPAT_PRECISION vec2 OutputSize;
uniform COMPAT_PRECISION vec2 TextureSize;
uniform COMPAT_PRECISION vec2 InputSize;
void main()
{
    vec2 _otexCoord;
    _r0005 = VertexCoord.x*MVPMatrix[0];
    _r0005 = _r0005 + VertexCoord.y*MVPMatrix[1];
    _r0005 = _r0005 + VertexCoord.z*MVPMatrix[2];
    _r0005 = _r0005 + VertexCoord.w*MVPMatrix[3];
    _oPosition1 = _r0005;
    _otexCoord = TexCoord.xy;
    gl_Position = _r0005;
    TEX0.xy = TexCoord.xy;
} 
#elif defined(FRAGMENT)

#if __VERSION__ >= 130
#define COMPAT_VARYING in
#define COMPAT_TEXTURE texture
out vec4 FragColor;
#else
#define COMPAT_VARYING varying
#define FragColor gl_FragColor
#define COMPAT_TEXTURE texture2D
#endif

#ifdef GL_ES
#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
#else
precision mediump float;
#endif
#define COMPAT_PRECISION mediump
#else
#define COMPAT_PRECISION
#endif
struct input_dummy {
    vec2 _video_size;
    vec2 _texture_size;
    vec2 _output_dummy_size;
};
vec4 _ret_0;
vec2 _TMP1;
uniform sampler2D Texture;
input_dummy _IN1;
float _x0007;
vec2 _TMP10;
float _a0011;
vec2 _c0017;
COMPAT_VARYING vec4 TEX0;
 
uniform int FrameDirection;
uniform int FrameCount;
uniform COMPAT_PRECISION vec2 OutputSize;
uniform COMPAT_PRECISION vec2 TextureSize;
uniform COMPAT_PRECISION vec2 InputSize;
void main()
{
    vec2 _texel;
    vec2 _texel_floored;
    float _scale;
    vec2 _s;
    float _region_range;
    vec2 _center_dist;
    vec2 _f;
    vec2 _mod_texel;
    _texel = TEX0.xy*TextureSize;
    _texel_floored = floor(_texel);
    _x0007 = OutputSize.y/InputSize.y;
    _scale = floor(_x0007);
    _s = fract(_texel);
    _region_range = 5.00000000E-01 - 5.00000000E-01/_scale;
    _center_dist = _s - 5.00000000E-01;
    _a0011 = -_region_range;
    _TMP1 = min(vec2(_region_range, _region_range), _center_dist);
    _TMP10 = max(vec2(_a0011, _a0011), _TMP1);
    _f = (_center_dist - _TMP10)*_scale + 5.00000000E-01;
    _mod_texel = _texel_floored + _f;
    _c0017 = _mod_texel/TextureSize;
    _ret_0 = COMPAT_TEXTURE(Texture, _c0017);
    FragColor = _ret_0;
    return;
} 
#endif
